---
  - name: Play for Install Nginx on WebServers
    hosts: web:app:db
    gather_facts: yes
    vars:
      custom_heading: "Welcome To DevOps Training Batch 23 By Sreeharsha Veerapalli - Testing Jinja"
      todays_date: "{{ ansible_facts['date_time']['date'] }}"
      host_name: "{{ ansible_facts['hostname'] }}"
      fqdn_name: "{{ ansible_facts['fqdn'] }}"
      friends: ['Sree','Harsha','Raju', 'Kumar']
    tasks:
       - name: Run Apt Update
         shell: apt update && apt install -y python-apt net-tools

       - name: Get-IP-Address
         shell: ifconfig | grep -i inet | head -1 | tr -s " " | cut -d " " -f 3
         register: ip_address

       - name: Install Nginx Server
         apt: >
           name=nginx
           state=present
       - name: Copy the files to index destination folder.
         template: >
            src=/tmp/ansibletemplatetesting/index.j2
            dest=/var/www/html/index.nginx-debian.html
            owner=root
            group=root
            mode=0644
       - name: Copy the style files to destination folder.
         copy: >
            src=/tmp/ansibletemplatetesting/style.css
            dest=/var/www/html/style.css
            owner=root
            group=root
            mode=0644
       - name: Copy the javascript files to destination folder.
         copy: >
            src=/tmp/ansibletemplatetesting/scorekeeper.js
            dest=/var/www/html/scorekeeper.js
            owner=root
            group=root
            mode=0644
       - name: restart nginx
         command: service nginx restart
